[Interface]
PrivateKey = CHANGE_ME_CLIENT_PRIVATE_KEY
Address = <VPN_CLIENT_IP>/32
DNS = <VPN_SERVER_IP>

[Peer]
PublicKey = CHANGE_ME_SERVER_PUBLIC_KEY
Endpoint = vpn.example.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
